[project]
name = "assinaturas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "pyqt5>=5.15.11",
    "sqlmodel>=0.0.22",
]
